---
title: "Connectivity Analyses"
author: "Müller, Ormazabal, Sellhorn, Wagner"
date: today
abstract: "This is the research workbook for our connectivity analyses."
format:
  html:
    theme: pulse
    embed-resources: true
    toc-location: left
    toc: true
    html-math-method: katex
    toc-title: Contents
    page-layout: full
    fig-width: 6
notebook-links: false
comments:
  hypothesis: true
---



# Method and Data

## Method
We analyzed 1,447 annual reports of EURO Stoxx 600 firms from 2018 to 2022.

We then manually classified different sections of the reports:

* Financial Statements and Notes
* Auditor's Report

Finally, we searched for different climate-related keywords:
{{< embed output-analyses.ipynb#search-patterns >}}



## Documents
::: {.panel-tabset}
### Sample selection
We distributed the EURO Stoxx 600 firms to student assistants to extract information on the structure of annual reports.
So far, this resulted in the following documents sample: 

1. after removing not readable pdfs (which is probably to sracping problems that can be fixed manually),
2. pdfs where no text was scanned, and 
3. pdfs with too little words(documents where the average clean text characters are less than 1,500 in a document).
{{< embed output-analyses.ipynb#tbl-documents-sample >}}


### Descriptives
{{< embed output-analyses.ipynb#fig-fig202309281148 >}}
:::




# Results

## Keywords over time (1)
::: {.panel-tabset}
### FS+Notes and Audit
{{< embed output-analyses.ipynb#fig-fig202310061330 >}}

### FS+Notes and Audit (no hits at all)
{{< embed output-analyses.ipynb#fig-fig202310061332 >}}

### By keyword
{{< embed output-analyses.ipynb#fig-fig202310061333 >}}
:::


## Keywords over time (2)
::: {.panel-tabset}
### FS+Notes and Audit
{{< embed output-analyses.ipynb#fig-fig202309281056 >}}

### FS+Notes and Audit
{{< embed output-analyses.ipynb#fig-fig202310061312 >}}

### FS+Notes and Audit (per Page)
{{< embed output-analyses.ipynb#fig-fig202310061313 >}}

### Full AR
{{< embed output-analyses.ipynb#fig-fig202309271823 >}}

### Full AR (per Page)
{{< embed output-analyses.ipynb#fig-fig202309281057 >}}
:::


## Climate alignment
::: {.panel-tabset}
### By ETS participation
{{< embed output-analyses.ipynb#fig-fig202310061334 >}}

### By MSCI Climate Exposure Score
{{< embed output-analyses.ipynb#fig-fig202310061335 >}}

### By MSCI Climate Exposure Score Quartiles
{{< embed output-analyses.ipynb#fig-fig202310061336 >}}

### By MSCI Climate Exposure Score Quartiles over time
{{< embed output-analyses.ipynb#fig-fig202310061337 >}}
:::


## Climate connectivity
::: {.panel-tabset}
### By MSCI Emission Disclosure Scores
{{< embed output-analyses.ipynb#fig-fig202310061338 >}}

### By MSCI Emission Disclosure Scores by keyword
{{< embed output-analyses.ipynb#fig-fig202310061339 >}}

### By Keyword Hits outside of FS and Audit
{{< embed output-analyses.ipynb#fig-fig202310061340 >}}

### By SRN ESRS Readiness
{{< embed output-analyses.ipynb#fig-fig202310061341 >}}
:::




## Relative location of keywords in FS+Notes
This graph shows the relative location (0%: first page, 100%: last page) in the F/S + Notes section.
{{< embed output-analyses.ipynb#fig-fig202309282020 >}}


## Keyword ranking
::: {.panel-tabset}
### Ranking
{{< embed output-analyses.ipynb#fig-fig202309281109 >}}

### In FS+Notes and Audit
{{< embed output-analyses.ipynb#fig-fig202309281112 >}}

### Full AR
{{< embed output-analyses.ipynb#fig-fig202309281111 >}}
:::